services:
  # === PRODUCT SERVICE ===
  product-db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - pos-net

  product-service:
    build: ./microservices/product-service
    container_name: product-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@product-db:5432/productdb
      REDIS_HOST: redis
    depends_on:
      - product-db
      - redis
    ports:
      - "3001:3000"
    networks:
      - pos-net

  # === SALES SERVICE ===
  sales-db:
    image: postgres
    container_name: sales-db
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - sales-db-data:/var/lib/postgresql/data
    networks:
      - pos-net

  sales-service:
    build: ./microservices/sales-service
    container_name: sales-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@sales-db:5432/salesdb
      REDIS_HOST: redis
    depends_on:
      - sales-db
      - redis
    ports:
      - "3002:3000"
    networks:
      - pos-net

  # === INVENTORY SERVICE ===
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - pos-net

  inventory-service:
    build: ./microservices/inventory-service
    container_name: inventory-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@inventory-db:5432/inventorydb
      REDIS_HOST: redis
    depends_on:
      - inventory-db
      - redis
    ports:
      - "3003:3000"
    networks:
      - pos-net

  # === STORE SERVICE ===
  store-db:
    image: postgres
    container_name: store-db
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - store-db-data:/var/lib/postgresql/data
    networks:
      - pos-net

  store-service:
    build: ./microservices/store-service
    container_name: store-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@store-db:5432/storedb
      REDIS_HOST: redis
    depends_on:
      - store-db
      - redis
    ports:
      - "3004:3000"
    networks:
      - pos-net

  # === REDIS SERVICE ===
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pos-net

# === VOLUMES PERSISTENTS ===
volumes:
  product-db-data:
  sales-db-data:
  inventory-db-data:
  store-db-data:

    # === RÉSEAU PRIVÉ ===
networks:
  pos-net:
    driver: bridge
