services:
  # === PRODUCT SERVICE ===
  product-db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  product-service:
    build: ./microservices/product-service
    container_name: product-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@product-db:5432/productdb
      REDIS_HOST: redis
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3001:3000"
    networks:
      - pos-net

  # === SALE SERVICE ===
  sale-db:
    image: postgres
    container_name: sale-db
    environment:
      POSTGRES_DB: saledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - sale-db-data:/var/lib/postgresql/data
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sale-service:
    build: ./microservices/sale-service
    container_name: sale-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@sale-db:5432/saledb
      REDIS_HOST: redis
    depends_on:
      sale-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3002:3000"
    networks:
      - pos-net

  # === INVENTORY SERVICE ===
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory-service:
    build: ./microservices/inventory-service
    container_name: inventory-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@inventory-db:5432/inventorydb
      REDIS_HOST: redis
    depends_on:
      inventory-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3003:3000"
    networks:
      - pos-net

  # === CUSTOMER SERVICE ===
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - customer-db-data:/var/lib/postgresql/data
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-service:
    build: ./microservices/customer-service
    container_name: customer-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@customer-db:5432/customerdb
      REDIS_HOST: redis
    depends_on:
      customer-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3004:3000"
    networks:
      - pos-net

  # === CART SERVICE ===
  cart-db:
    image: postgres
    container_name: cart-db
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - cart-db-data:/var/lib/postgresql/data
      - ./output:/app/output
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cart-service:
    build: ./microservices/cart-service
    container_name: cart-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@cart-db:5432/cartdb
      REDIS_HOST: redis
    depends_on:
      cart-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3005:3000"
    networks:
      - pos-net

  # === CART SERVICE INSTANCE 2 ===
  cart-service-2:
    build: ./microservices/cart-service
    container_name: cart-service-2
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@cart-db:5432/cartdb
      REDIS_HOST: redis
    depends_on:
      cart-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3007:3000"
    networks:
      - pos-net

  # === CHECKOUT SERVICE ===
  checkout-db:
    image: postgres
    container_name: checkout-db
    environment:
      POSTGRES_DB: checkoutdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - checkout-db-data:/var/lib/postgresql/data
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  checkout-service:
    build: ./microservices/checkout-service
    container_name: checkout-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@checkout-db:5432/checkoutdb
      REDIS_HOST: redis
    depends_on:
      checkout-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3006:3000"
    networks:
      - pos-net

  # === STORE SERVICE ===
  store-db:
    image: postgres
    container_name: store-db
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XRoot123
    volumes:
      - store-db-data:/var/lib/postgresql/data
    networks:
      - pos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  store-service:
    build: ./microservices/store-service
    container_name: store-service
    environment:
      DATABASE_URL: postgres://postgres:XRoot123@store-db:5432/storedb
      REDIS_HOST: redis
    depends_on:
      store-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3008:3000"
    networks:
      - pos-net

  # === API GATEWAY ===
  api-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - product-service
      - sale-service
      - inventory-service
      - customer-service
      - cart-service
      - cart-service-2
      - checkout-service
      - store-service
    networks:
      - pos-net

  # === FAKE DATA GENERATION ===
  generatedata:
    build: ./tools/generatedata
    container_name: generate-data
    command: [ "node", "migrate.js" ]
    depends_on:
      cart-db:
        condition: service_healthy
    networks:
      - pos-net

  # === REDIS SERVICE ===
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pos-net

  # === PROMETHEUS ===
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pos-net

  # === GRAFANA ===
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=error
      - GF_LOG_MODE=console
    networks:
      - pos-net

# === VOLUMES PERSISTENTS ===
volumes:
  product-db-data:
  sale-db-data:
  inventory-db-data:
  customer-db-data:
  cart-db-data:
  checkout-db-data:
  store-db-data:

    # === RÉSEAU PRIVÉ ===
networks:
  pos-net:
    driver: bridge
