services:
  app:
    build: .
    container_name: pos-console-app
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/postgres
    working_dir: /app
    command: node src/index.js
    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
