global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pos-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['pos-app1:3000']
      - targets: ['pos-app2:3000']
      - targets: ['pos-app3:3000']
