@startuml VueCasUtilisation
left to right direction
actor "Employe" as e
rectangle "Application POS" {
  usecase "Consulter le rapport des magasins" as UC1
  usecase "Consulter les provisions de l'entrepot" as UC2
  usecase "Faire une demande de réapprovsionnement" as UC3
  usecase "Consulter le tableau de bord" as UC4
}
e -- UC1
e -- UC2
e -- UC3
e -- UC4
@enduml
