@startuml VueCasUtilisationClient

left to right direction

actor "Client" as c

rectangle "Application POS" {
  usecase "Créer un compte client" as UC1
  usecase "Ajouter des articles au panier" as UC2
  usecase "Retirer des articles du panier" as UC3
  usecase "Valider la commande" as UC4
}

c -- UC1
c -- UC2
c -- UC3
c -- UC4

@enduml
