@startuml VuePackagePOS

title POS Microservices - Implementation View

skinparam packageStyle rectangle

package "POS Microservices" {

  ' === Product Service ===
  package "Product Service" {

    package "data access layer" {
      class ProductModel
    }

    package "business logic" {
      class ProductService
    }

    package "presentation layer" {
      class ProductController
    }

    ProductController --> ProductService : uses
    ProductService --> ProductModel : interacts
  }

  ' === Sale Service ===
  package "Sale Service" {

    package "data access layer" {
      class SaleModel
    }

    package "business logic" {
      class SaleService
    }

    package "presentation layer" {
      class SaleController
    }

    SaleController --> SaleService : uses
    SaleService --> SaleModel : interacts
  }

  ' === Inventory Service ===
  package "Inventory Service" {

    package "data access layer" {
      class InventoryModel
    }

    package "business logic" {
      class InventoryService
    }

    package "presentation layer" {
      class InventoryController
    }

    InventoryController --> InventoryService : uses
    InventoryService --> InventoryModel : interacts
  }

  ' === Customer Service ===
  package "Customer Service" {

    package "data access layer" {
      class CustomerModel
    }

    package "business logic" {
      class CustomerService
    }

    package "presentation layer" {
      class CustomerController
    }

    CustomerController --> CustomerService : uses
    CustomerService --> CustomerModel : interacts
  }

  ' === Cart Service ===
  package "Cart Service" {

    package "data access layer" {
      class CartModel
    }

    package "business logic" {
      class CartService
    }

    package "presentation layer" {
      class CartController
    }

    CartController --> CartService : uses
    CartService --> CartModel : interacts
  }

  ' === Checkout Service ===
  package "Checkout Service" {

    package "data access layer" {
      class CheckoutModel
    }

    package "business logic" {
      class CheckoutService
    }

    package "presentation layer" {
      class CheckoutController
    }

    CheckoutController --> CheckoutService : uses
    CheckoutService --> CheckoutModel : interacts
  }

    ' === Store Service ===
  package "Store Service" {

    package "data access layer" {
      class StoreModel
    }

    package "business logic" {
      class StoreService
    }

    package "presentation layer" {
      class StoreController
    }

    StoreController --> StoreService : uses
    StoreService --> StoreModel : interacts
  }
}

@enduml
