@startuml VuePackagePOS

package "Application" {
  
 package "data access layer" {
    package "models" {
      class ParentStore
      class Product
      class Replenishment
      class Sale
      class Stock
      class Store
      class Warehouse
    }
 }

  package "business logic" {
    package "controllers" {
      class ParentStoreController
      class ReplenishmentController
      class StoreController
      class WarehouseController
    }

    package "services" {
      class ParentStoreService
      class ReplenishmentService
      class StockService
      class StoreService
      class WarehouseService
    }
  }

  package "presentation layer" {
    package "routes" {
      class ParentStoreRoutes
      class ReplenishmentRoutes
      class StoreRoutes
      class WarehouseRoutes
    }

    package "views" {
      class ParentStoreDashboardView
      class ReplenishmentView
      class StoreDetailsView
      class WarehouseStockView
    }
  }
}

controllers --> services : uses
services --> models : interacts
routes --> controllers : calls
views --> routes : navigates
models --> controllers : provides data

@enduml
