@startuml ComposantsPOS

package "Application POS (Node.js)" {
  [Console UI (Inquirer.js)] --> [Produit Service]
  [Console UI (Inquirer.js)] --> [Catégorie Service]
}

[Produit Service] --> [Modèle Sequelize: Product]
[Catégorie Service] --> [Modèle Sequelize: Category]

database "Base de données PostgreSQL" as DB

[Modèle Sequelize: Product] --> DB
[Modèle Sequelize: Category] --> DB

@enduml
