@startuml POS_Product_Category
top to bottom direction

class Product {
  +Integer id
  +String name
  +Float price
  +Integer stockQuantity
}

class Category {
  +Integer id
  +String name
}

Category "1" --> "*" Product : owns

@enduml
